# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0002_studentticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentTicket',
        ),
    ]
