# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0003_delete_studentticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMTS.studentInfo')),
            ],
        ),
    ]
