# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0004_studentticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='briefDescription',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='resid_hall',
            field=models.CharField(max_length=200),
        ),
    ]
