# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0005_auto_20161106_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='rankOfTicket',
            field=models.IntegerField(),
        ),
    ]
