# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0006_auto_20161106_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='studentEmail',
            field=models.EmailField(max_length=250),
        ),
    ]
