# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0007_auto_20161116_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='studentEmail',
            field=models.CharField(max_length=250),
        ),
    ]
