# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0009_auto_20161116_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='studentEmail',
        ),
    ]
