# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0010_remove_studentinfo_studentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='studentEmail',
            field=models.EmailField(default='', max_length=250),
        ),
    ]
