# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0013_auto_20161121_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='resid_hall',
            field=models.CharField(choices=[('US', 'University Suites'), ('UT', 'University Towers'), ('VT', 'Viking Towers'), ('VV', 'Viking Village')], default='', max_length=12),
        ),
    ]
