# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0014_auto_20161121_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='issues',
            field=models.CharField(choices=[('BD', 'Bed'), ('DSK', 'Desk'), ('DSSR', 'Dresser'), ('CLST', 'Closet'), ('MTTRESS', 'Mattress'), ('WNDOW', 'Window'), ('WNDOWBLNDS', 'Window_Blinds'), ('WLLS', 'Walls'), ('MCROFRDGE', 'Microfridge'), ('MCROWVE', 'Microwave'), ('DOORS', 'Doors'), ('FLOORS', 'Floors'), ('LCKS', 'Locks'), ('BTHROOMSHWR', 'Bathroom_Shower'), ('BTHROOMWLLS', 'Bathroom_walls'), ('BTHROOMTLIT', 'Bathroom_toilet'), ('AC', 'Air_Conditioning_Unit'), ('SNKMRROR', 'Sink/Mirror'), ('ELECTOUTLETS', 'Electrical_Outlets'), ('LGHTS', 'Lights')], default='', max_length=12),
        ),
    ]
