# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0016_auto_20161121_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='rankOfTicket',
            field=models.CharField(default='', max_length=1),
        ),
    ]
