# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0017_auto_20161121_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='resid_hall',
            new_name='Residence_Hall',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='briefDescription',
            new_name='brief_Description',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='rankOfTicket',
            new_name='rank_Of_Ticket',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='room_num',
            new_name='room_Number',
        ),
    ]
