# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMTS', '0018_auto_20161121_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='occupancy',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=10),
        ),
    ]
